spring.application.name=rbac

# Permitir a execução dos comandos no data.sql
spring.sql.init.mode=always

# Configurações do Banco de Dados H2 (apenas para testes)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA (Java Persistence API) Configurações
spring.jpa.hibernate.ddl-auto=update
# Atrasa a execução do script no data.sql para fazer após a criação das tabelas
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# Configurações do Spring Security
# Define a URL de login personalizada (caso precise ser usada em outra parte do sistema)
spring.security.form-login.page=/login

# Configurações de logging (opcional)
logging.level.org.springframework.security=DEBUG

# Configuração de mensagem para login personalizado (opcional)
spring.messages.basename=messages
